#!/usr/bin/env bash

# Install Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
rm -f ~/.zprofile; touch ~/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install Brew packages
brew bundle

# Install npm packages
npm install -g yarn

# Install mfa
pip3 install mfa

# Configure finder
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Configure git
cp .gitconfig ~
cp .gitignore ~

# Install zim
touch ~/.hushlogin
chsh -s /bin/zsh
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

# Install zinit
curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh | zsh

# Install powerline font
wget https://gist.github.com/justinmayer/7537418/raw/f397bf7440796597880e7aa153d693768ad70ef5/Menlo-for-Powerline.zip -O /tmp/Menlo-for-Powerline.zip
unzip /tmp/Menlo-for-Powerline.zip -d /Library/Fonts
rm /tmp/Menlo-for-Powerline.zip

# Install spicetify
git clone https://github.com/morpheusthewhite/spicetify-themes ~/spicetify_data/Themes
sed -i -e 's/SpicetifyDefault/Dark/g' ~/spicetify_data/config.ini
spicetify backup apply

# Install sdkman
curl -s "https://get.sdkman.io" | zsh

sudo gem install mdless

sudo softwareupdate -ia
