#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/david.molinero/.profile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew bundle

cp .gitconfig ~

# Install Spicetify
git clone https://github.com/morpheusthewhite/spicetify-themes ~/spicetify_data/Themes
sed -i -e 's/SpicetifyDefault/Dark/g' ~/spicetify_data/config.ini
spicetify backup apply

# Install Alfred
wget https://cachefly.alfredapp.com/Alfred_3.8.6_972.dmg -O /tmp/Alfred.dmg
hdiutil mount /tmp/Alfred
mv /Volumes/Alfred/Alfred\ 3.app/ /Applications/
hdiutil unmount /Volumes/Alfred/
rm /tmp/Alfred.dmg

sudo softwareupdate -ia
