#!/usr/bin/env bash

# Install Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
rm -f ~/.zprofile; touch ~/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install Brew packages
brew bundle

# Configure git
cp .gitconfig ~
cp .gitignore ~

# Install Zim
touch ~/.hushlogin
chsh -s /bin/zsh
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

# Install Powerline font
wget https://gist.github.com/justinmayer/7537418/raw/f397bf7440796597880e7aa153d693768ad70ef5/Menlo-for-Powerline.zip -O /tmp/Menlo-for-Powerline.zip
unzip /tmp/Menlo-for-Powerline.zip -d /Library/Fonts
rm /tmp/Menlo-for-Powerline.zip

# Install Spicetify
git clone https://github.com/morpheusthewhite/spicetify-themes ~/spicetify_data/Themes
sed -i -e 's/SpicetifyDefault/Dark/g' ~/spicetify_data/config.ini
spicetify backup apply

# Install Alfred
wget https://cachefly.alfredapp.com/Alfred_3.8.6_972.dmg -O /tmp/Alfred.dmg
hdiutil mount /tmp/Alfred
mv /Volumes/Alfred/Alfred\ 3.app/ /Applications/
hdiutil unmount /Volumes/Alfred/
rm /tmp/Alfred.dmg

# Configure nvm
rm -f ~/.nvm.zsh; cp .nvm.zsh ~
echo '. ~/.nvm.zsh' >> ~/.zprofile

sudo softwareupdate -ia
