tap "common-fate/granted"

brew "ag"
brew "awscli"
brew "bat"
brew "blackbox"
brew "rs/tap/curlie"
brew "diff-so-fancy"
brew "docker"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gpg"
brew "granted"
brew "htop-osx"
brew "ijq"
brew "jq"
brew "khanhas/tap/spicetify-cli"
brew "mas"
brew "miller"
brew "nvm"
brew "terminal-notifier"
brew "thefuck"
brew "tldr"
brew "trash"
brew "tree"
brew "warrensbox/tap/tfswitch"
brew "wget"
brew "wifi-password"
brew "youplot"
brew "yq"
brew "z"

tap "homebrew/cask"

cask "ace-link"
cask "appcleaner"
cask "authy"
cask "box-drive"
cask "caption"
cask "devbook"
cask "dropbox"
cask "easy-move-plus-resize"
cask "fromscratch"
cask "hiddenbar"
cask "iterm2"
cask "itsycal"
cask "jetbrains-toolbox"
cask "kap"
cask "macdown"
cask "maestral"
cask "obsidian"
cask "postman"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "raycast"
cask "skype"
cask "stats"
cask "sourcetree"
cask "spotify"
cask "telegram-desktop"
cask "transmission"
cask "typora"
cask "webstorm"
cask "zoom"

mas "1Password", id: 443987910
mas "clear", id: 504544917
mas "meeter", id: 1510445899
mas "pastebot", id: 1179623856
mas "reeder 3", id: 880001334
mas "slack", id: 803453959
mas "skitch", id: 425955336
mas "the unarchiver", id: 425424353
mas "things", id: 904280696
mas "todo", id: 1274495053
mas "whatsapp", id: 1147396723
